module.exports = {
    "Members": {
        6: "Kasumi Toyama",
        7: "Tae Hanazono",
        8: "Rimi Ushigome",
        9: "Saaya Yamabuki",
        10: "Arisa Ichigaya",
        11: "Ran Mitake",
        12: "Moca Aoba",
        13: "Himari Uehara",
        14: "Tomoe Udagawa",
        15: "Tsugumi Hazawa",
        16: "Kokoro Tsurumaki",
        17: "Kaoru Seta",
        18: "Hagumi Kitazawa",
        19: "Kanon Matsubara",
        20: "Michelle",
        21: "Aya Maruyama",
        22: "Hina Hikawa",
        23: "Chisato Shirasagi",
        24: "Maya Yamato",
        25: "Eve Wakamiya",
        26: "Yukina Minato",
        27: "Sayo Hikawa",
        28: "Lisa Imai",
        29: "Ako Udagawa",
        30: "Rinko Shirokane"
    },
    "MemberSearchTerms": {
        "kasumi": 6,
        "tae": 7,
        "rimi": 8,
        "saaya": 9,
        "arisa": 10,
        "ran": 11,
        "moca": 12,
        "himari": 13,
        "tomoe": 14,
        "tsugumi": 15,
        "kokoro": 16,
        "kaoru": 17,
        "hagumi": 18,
        "kanon": 19,
        "michelle": 20,
        "aya": 21,
        "hina": 22,
        "chisato": 23,
        "maya": 24,
        "eve": 25,
        "yukina": 26,
        "sayo": 27,
        "lisa": 28,
        "ako": 29,
        "rinko": 30
    }
}